import json
from pydantic import ValidationError
import pytest
from app.core.models import Core_Order

from app.vtex.vtex import VTEX, VtexIntegration


@pytest.fixture(scope="function")
def test_order():
    return {
        "orderId": "1275500509905-01",
        "sequence": "509905",
        "marketplaceOrderId": "",
        "sellerOrderId": "00-1275500509905-01",
        "origin": "Marketplace",
        "salesChannel": "1",
        "status": "canceled",
        "statusDescription": "Cancelado",
        "creationDate": "2022-11-11T14:24:26.946Z",
        "lastChange": "2022-11-11T14:32:14.276Z",
        "orderGroup": "1275500509905",
        "totals": [
            {"id": "Items", "name": "Total de los items", "value": 50300},
            {"id": "Discounts", "name": "Total de descuentos", "value": 0},
            {"id": "Shipping", "name": "Costo total del envío", "value": 142417},
            {"id": "Tax", "name": "Costo total del cambio", "value": 0},
        ],
        "items": [
            {
                "uniqueId": "89DAB2B2904145828CE99D7C773F0240",
                "id": "5927",
                "productId": "883",
                "quantity": 1,
                "seller": "1",
                "name": "PELOTA INFLABLE SPORT PLAYA BESTWAY 2097/31004 2097/31004 BESTWAY PELOTA SPORT 2020 VARIOS UNICO",
                "additionalInfo": {
                    "dimension": {
                        "cubicweight": 1,
                        "height": 35,
                        "length": 12,
                        "weight": 1200,
                        "width": 28,
                    }
                },
                "assemblies": [],
                "imageUrl": "https://calzadosnicoar.vteximg.com.br/arquivos/ids/42399444-55-55/4922a_luuhxj.jpg?v=638037321446200000",
                "listPrice": 50300,
                "tax": 0,
                "freightCommission": 0,
                "parentItemIndex": None,
                "taxCode": "",
                "rewardValue": 0,
                "price": 50300,
                "manualPrice": None,
                "detailUrl": "/2097-31004-bestway-pelota-sport-2020-varios-unico-628925/p",
                "priceValidUntil": None,
                "commission": 0,
                "sellerSku": "5927",
                "refId": "628925#UNICO#VARIOS",
                "costPrice": 50319,
                "itemAttachment": {"content": {}, "name": None},
                "lockId": "00-1275500509905-01",
                "preSaleDate": None,
                "attachments": [],
                "unitMultiplier": 1,
                "params": [],
                "priceDefinition": {
                    "sellingPrices": [{"value": 50300, "quantity": 1}],
                    "calculatedSellingPrice": 50300,
                    "total": 50300,
                },
                "bundleItems": [],
                "parentAssemblyBinding": None,
                "measurementUnit": "un",
                "shippingPrice": None,
                "sellingPrice": 50300,
                "components": [],
                "offerings": [],
                "serialNumbers": None,
                "ean": None,
                "priceTags": [],
                "callCenterOperator": None,
                "isGift": False,
            }
        ],
        "clientProfileData": {
            "id": "clientProfileData",
            "email": "2417526c8928426db0badf3878b700b6@ct.vtex.com.br",
            "firstName": "Pablo",
            "lastName": "Iaria",
            "document": "24352845",
            "phone": "+5491136814143",
            "customerClass": None,
            "stateInscription": None,
            "userProfileVersion": None,
            "documentType": "dni",
            "corporateName": None,
            "userProfileId": "25090b7e-dccb-4e50-b551-a9d41ae1ca6b",
            "tradeName": None,
            "corporatePhone": None,
            "isCorporate": False,
            "corporateDocument": None,
        },
        "shippingData": {
            "id": "shippingData",
            "address": {
                "addressType": "residential",
                "receiverName": "Pablo Iaria",
                "addressId": "8340882395830",
                "postalCode": "1896",
                "city": "City Bell",
                "state": "Buenos Aires",
                "country": "ARG",
                "street": "13c",
                "number": "1215",
                "complement": None,
                "neighborhood": "City Bell",
                "geoCoordinates": [-58.051658630371094, -34.86330032348633],
                "entityId": None,
                "reference": "entre calles 461c y 461d",
                "versionId": None,
            },
            "logisticsInfo": [
                {
                    "selectedSla": "clicOH Envío a Domicilio",
                    "deliveryCompany": "clicOH Envío a Domicilio",
                    "slas": [
                        {
                            "id": "clicOH Envío a Domicilio",
                            "name": "clicOH Envío a Domicilio",
                            "deliveryChannel": "delivery",
                            "pickupStoreInfo": {
                                "address": None,
                                "dockId": None,
                                "isPickupStore": False,
                                "friendlyName": None,
                                "additionalInfo": None,
                            },
                            "pickupPointId": None,
                            "polygonName": "",
                            "shippingEstimate": "7bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 142417,
                            "transitTime": "7bd",
                        },
                        {
                            "id": "clicOH Envío a Punto de Recogida",
                            "name": "clicOH Envío a Punto de Recogida",
                            "deliveryChannel": "delivery",
                            "pickupStoreInfo": {
                                "address": None,
                                "dockId": None,
                                "isPickupStore": False,
                                "friendlyName": None,
                                "additionalInfo": None,
                            },
                            "pickupPointId": None,
                            "polygonName": "",
                            "shippingEstimate": "7bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 142417,
                            "transitTime": "7bd",
                        },
                        {
                            "id": "Andreani Envío a Domicilio",
                            "name": "Andreani Envío a Domicilio",
                            "deliveryChannel": "delivery",
                            "pickupStoreInfo": {
                                "address": None,
                                "dockId": None,
                                "isPickupStore": False,
                                "friendlyName": None,
                                "additionalInfo": None,
                            },
                            "pickupPointId": None,
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 145945,
                            "transitTime": "5bd",
                        },
                        {
                            "id": "Retiro en sucursal (CLICOH-6)",
                            "name": "Retiro en sucursal (CLICOH-6)",
                            "deliveryChannel": "pickup-in-point",
                            "pickupStoreInfo": {
                                "address": {
                                    "addressType": "pickup",
                                    "receiverName": None,
                                    "addressId": "CLICOH-6",
                                    "postalCode": "1900",
                                    "city": "La Plata",
                                    "state": None,
                                    "country": "Argentina",
                                    "street": None,
                                    "number": None,
                                    "complement": None,
                                    "neighborhood": "Argentina",
                                    "geoCoordinates": [-57.95586, -34.92048],
                                    "entityId": None,
                                    "reference": None,
                                    "versionId": None,
                                },
                                "dockId": "195f825",
                                "isPickupStore": True,
                                "friendlyName": "LaPlata2",
                                "additionalInfo": "1- Código clicOH 2- Nombre apellido destintario 3- DNI",
                            },
                            "pickupPointId": "1_CLICOH-6",
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 0,
                            "transitTime": "5bd",
                        },
                        {
                            "id": "Retiro en sucursal (CLICOH-78)",
                            "name": "Retiro en sucursal (CLICOH-78)",
                            "deliveryChannel": "pickup-in-point",
                            "pickupStoreInfo": {
                                "address": {
                                    "addressType": "pickup",
                                    "receiverName": None,
                                    "addressId": "CLICOH-78",
                                    "postalCode": "1878",
                                    "city": "Quilmes Oeste",
                                    "state": None,
                                    "country": "Argentina",
                                    "street": None,
                                    "number": "1206",
                                    "complement": None,
                                    "neighborhood": "Argentina",
                                    "geoCoordinates": [-58.27062, -34.733],
                                    "entityId": None,
                                    "reference": None,
                                    "versionId": None,
                                },
                                "dockId": "195f825",
                                "isPickupStore": True,
                                "friendlyName": "GBA29",
                                "additionalInfo": "1- Código clicOH 2- Nombre apellido destintario 3- DNI",
                            },
                            "pickupPointId": "1_CLICOH-78",
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 0,
                            "transitTime": "5bd",
                        },
                        {
                            "id": "Retiro en sucursal (CLICOH-539)",
                            "name": "Retiro en sucursal (CLICOH-539)",
                            "deliveryChannel": "pickup-in-point",
                            "pickupStoreInfo": {
                                "address": {
                                    "addressType": "pickup",
                                    "receiverName": None,
                                    "addressId": "CLICOH-539",
                                    "postalCode": "1881",
                                    "city": "San Francisco Solano",
                                    "state": "Provincia de Buenos Aires",
                                    "country": "Argentina",
                                    "street": "Calle 844",
                                    "number": "1918",
                                    "complement": "Av. 844 N 1918, B1984 San Francisco Solano, Provincia de Buenos Aires, Argentina",
                                    "neighborhood": "Argentina",
                                    "geoCoordinates": [-58.30547, -34.77638],
                                    "entityId": None,
                                    "reference": None,
                                    "versionId": None,
                                },
                                "dockId": "195f825",
                                "isPickupStore": True,
                                "friendlyName": "GBA43",
                                "additionalInfo": "1- Código clicOH 2- Nombre apellido destintario 3- DNI",
                            },
                            "pickupPointId": "1_CLICOH-539",
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 0,
                            "transitTime": "5bd",
                        },
                        {
                            "id": "Retiro en sucursal (CLICOH-77)",
                            "name": "Retiro en sucursal (CLICOH-77)",
                            "deliveryChannel": "pickup-in-point",
                            "pickupStoreInfo": {
                                "address": {
                                    "addressType": "pickup",
                                    "receiverName": None,
                                    "addressId": "CLICOH-77",
                                    "postalCode": "1849",
                                    "city": "Claypole",
                                    "state": None,
                                    "country": "Argentina",
                                    "street": None,
                                    "number": "606",
                                    "complement": None,
                                    "neighborhood": "Argentina",
                                    "geoCoordinates": [-58.33845, -34.80041],
                                    "entityId": None,
                                    "reference": None,
                                    "versionId": None,
                                },
                                "dockId": "195f825",
                                "isPickupStore": True,
                                "friendlyName": "GBA28",
                                "additionalInfo": "1- Código clicOH 2- Nombre apellido destintario 3- DNI",
                            },
                            "pickupPointId": "1_CLICOH-77",
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 0,
                            "transitTime": "5bd",
                        },
                        {
                            "id": "Retiro en sucursal (CLICOH-546)",
                            "name": "Retiro en sucursal (CLICOH-546)",
                            "deliveryChannel": "pickup-in-point",
                            "pickupStoreInfo": {
                                "address": {
                                    "addressType": "pickup",
                                    "receiverName": None,
                                    "addressId": "CLICOH-546",
                                    "postalCode": "1832",
                                    "city": "Lomas de Zamora",
                                    "state": "Provincia de Buenos Aires",
                                    "country": "Argentina",
                                    "street": "Calle Republica del Libano",
                                    "number": "41",
                                    "complement": "C. Republica del Libano 41, B1832BKA Lomas de Zamora, Provincia de Buenos Aires, Argentina",
                                    "neighborhood": "Argentina",
                                    "geoCoordinates": [-58.39793, -34.76156],
                                    "entityId": None,
                                    "reference": None,
                                    "versionId": None,
                                },
                                "dockId": "195f825",
                                "isPickupStore": True,
                                "friendlyName": "GBA48",
                                "additionalInfo": "1- Código clicOH 2- Nombre apellido destintario 3- DNI",
                            },
                            "pickupPointId": "1_CLICOH-546",
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 0,
                            "transitTime": "5bd",
                        },
                        {
                            "id": "Retiro en sucursal (CLICOH-14)",
                            "name": "Retiro en sucursal (CLICOH-14)",
                            "deliveryChannel": "pickup-in-point",
                            "pickupStoreInfo": {
                                "address": {
                                    "addressType": "pickup",
                                    "receiverName": None,
                                    "addressId": "CLICOH-14",
                                    "postalCode": "1832",
                                    "city": None,
                                    "state": None,
                                    "country": "Argentina",
                                    "street": None,
                                    "number": "546",
                                    "complement": None,
                                    "neighborhood": "Argentina",
                                    "geoCoordinates": [-58.4049, -34.76132],
                                    "entityId": None,
                                    "reference": None,
                                    "versionId": None,
                                },
                                "dockId": "195f825",
                                "isPickupStore": True,
                                "friendlyName": "pickup.demo",
                                "additionalInfo": "1- Código clicOH 2- Nombre apellido destintario 3- DNI",
                            },
                            "pickupPointId": "1_CLICOH-14",
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 0,
                            "transitTime": "5bd",
                        },
                        {
                            "id": "Retiro en sucursal (CLICOH-545)",
                            "name": "Retiro en sucursal (CLICOH-545)",
                            "deliveryChannel": "pickup-in-point",
                            "pickupStoreInfo": {
                                "address": {
                                    "addressType": "pickup",
                                    "receiverName": None,
                                    "addressId": "CLICOH-545",
                                    "postalCode": "1871",
                                    "city": "Dock Sud",
                                    "state": "Provincia de Buenos Aires",
                                    "country": "Argentina",
                                    "street": "12 de Octubre",
                                    "number": "580",
                                    "complement": "12 de Octubre 580, Dock Sud, Provincia de Buenos Aires, Argentina",
                                    "neighborhood": "Argentina",
                                    "geoCoordinates": [-58.35457, -34.65935],
                                    "entityId": None,
                                    "reference": None,
                                    "versionId": None,
                                },
                                "dockId": "195f825",
                                "isPickupStore": True,
                                "friendlyName": "GBA47",
                                "additionalInfo": "1- Código clicOH 2- Nombre apellido destintario 3- DNI",
                            },
                            "pickupPointId": "1_CLICOH-545",
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 0,
                            "transitTime": "5bd",
                        },
                        {
                            "id": "Retiro en sucursal (CLICOH-547)",
                            "name": "Retiro en sucursal (CLICOH-547)",
                            "deliveryChannel": "pickup-in-point",
                            "pickupStoreInfo": {
                                "address": {
                                    "addressType": "pickup",
                                    "receiverName": None,
                                    "addressId": "CLICOH-547",
                                    "postalCode": "1824",
                                    "city": "Lanús Oeste",
                                    "state": "Provincia de Buenos Aires",
                                    "country": "Argentina",
                                    "street": "Coronel D Elia",
                                    "number": "2045",
                                    "complement": "Cnel. D Elia 2045, B1822 Lanus, Provincia de Buenos Aires, Argentina",
                                    "neighborhood": "Argentina",
                                    "geoCoordinates": [-58.41204, -34.68826],
                                    "entityId": None,
                                    "reference": None,
                                    "versionId": None,
                                },
                                "dockId": "195f825",
                                "isPickupStore": True,
                                "friendlyName": "GBA49",
                                "additionalInfo": "1- Código clicOH 2- Nombre apellido destintario 3- DNI",
                            },
                            "pickupPointId": "1_CLICOH-547",
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 0,
                            "transitTime": "5bd",
                        },
                        {
                            "id": "Retiro en sucursal (CLICOH-61)",
                            "name": "Retiro en sucursal (CLICOH-61)",
                            "deliveryChannel": "pickup-in-point",
                            "pickupStoreInfo": {
                                "address": {
                                    "addressType": "pickup",
                                    "receiverName": None,
                                    "addressId": "CLICOH-61",
                                    "postalCode": "1137",
                                    "city": "ACF",
                                    "state": None,
                                    "country": "Argentina",
                                    "street": None,
                                    "number": "1482",
                                    "complement": None,
                                    "neighborhood": "Argentina",
                                    "geoCoordinates": [-58.38283, -34.62568],
                                    "entityId": None,
                                    "reference": None,
                                    "versionId": None,
                                },
                                "dockId": "195f825",
                                "isPickupStore": True,
                                "friendlyName": "CABA20",
                                "additionalInfo": "1- Código clicOH 2- Nombre apellido destintario 3- DNI",
                            },
                            "pickupPointId": "1_CLICOH-61",
                            "polygonName": "",
                            "shippingEstimate": "5bd",
                            "deliveryWindow": None,
                            "lockTTL": "12d",
                            "price": 0,
                            "transitTime": "5bd",
                        },
                    ],
                    "shipsTo": ["ARG"],
                    "deliveryIds": [
                        {
                            "courierId": "clicOH Envío a Domicilio",
                            "courierName": "clicOH Envío a Domicilio",
                            "dockId": "14c54ca",
                            "warehouseId": "15cf081",
                            "quantity": 1,
                            "accountCarrierName": "calzadosnicoar",
                        }
                    ],
                    "deliveryChannel": "delivery",
                    "pickupStoreInfo": {
                        "address": None,
                        "dockId": None,
                        "isPickupStore": False,
                        "friendlyName": None,
                        "additionalInfo": None,
                    },
                    "listPrice": 142417,
                    "sellingPrice": 142417,
                    "price": 142417,
                    "entityId": None,
                    "versionId": None,
                    "polygonName": "",
                    "pickupPointId": None,
                    "deliveryWindow": None,
                    "shippingEstimate": "7bd",
                    "lockTTL": "12d",
                    "itemIndex": 0,
                    "addressId": "8340882395830",
                    "shippingEstimateDate": "2022-11-22T14:26:34.9612854+00:00",
                    "transitTime": "7bd",
                }
            ],
            "selectedAddresses": [
                {
                    "addressType": "residential",
                    "receiverName": "Pablo Iaria",
                    "addressId": "8340882395830",
                    "postalCode": "1896",
                    "city": "City Bell",
                    "state": "Buenos Aires",
                    "country": "ARG",
                    "street": "13c",
                    "number": "1215",
                    "complement": None,
                    "neighborhood": "City Bell",
                    "geoCoordinates": [-58.051658630371094, -34.86330032348633],
                    "entityId": None,
                    "reference": "entre calles 461c y 461d",
                    "versionId": None,
                }
            ],
            "trackingHints": None,
        },
        "allowCancellation": False,
        "allowEdition": False,
        "cancelReason": "Compré por error",
        "packageAttachment": {"packages": []},
        "clicoh_client_id": 241,
        "clicoh_id": 915553,
        "clicoh_tracking_code": "DNBHW79514",
        "changes_history": [],
        "core_status_history": None,
        "store_id": "634d619c66590217312cb0de",
        "marketplace": {
            "baseURL": "http://oms.vtexinternal.com.br/api/oms?an=calzadosnicoar",
            "isCertified": None,
            "name": "calzadosnicoar",
        },
        "openTextField": None,
        "roundingError": 0,
        "taxData": None,
        "giftRegistryData": None,
        "storePreferencesData": {
            "countryCode": "ARG",
            "currencyCode": "ARS",
            "currencyFormatInfo": {
                "CurrencyDecimalDigits": 2,
                "CurrencyDecimalSeparator": ",",
                "CurrencyGroupSeparator": ".",
                "CurrencyGroupSize": 3,
                "StartsWithCurrencySymbol": True,
            },
            "currencyLocale": 11274,
            "currencySymbol": "$",
            "timeZone": "Argentina Standard Time",
        },
        "orderFormId": "719f67235f8f4e7591abcd329345567a",
        "invoiceData": None,
        "callCenterOperatorData": None,
        "checkedInPickupPointId": None,
        "ratesAndBenefitsData": {
            "id": "ratesAndBenefitsData",
            "rateAndBenefitsIdentifiers": [],
        },
        "customData": None,
        "invoicedDate": None,
        "marketplaceItems": [],
        "marketplaceServicesEndpoint": "http://oms.vtexinternal.com.br/api/oms?an=calzadosnicoar",
        "changesAttachment": None,
        "cancellationData": {
            "RequestedByUser": True,
            "RequestedBySystem": None,
            "RequestedBySellerNotification": None,
            "RequestedByPaymentNotification": None,
            "Reason": "Compré por error",
            "CancellationDate": "2022-11-11T14:32:05.9582265+00:00",
        },
        "paymentData": {
            "giftCards": [],
            "transactions": [
                {
                    "isActive": True,
                    "transactionId": "03EDF00D4EFA4D0EB24B0B4739049B9F",
                    "merchantName": "CALZADOSNICOAR",
                    "payments": [
                        {
                            "id": "595E42E4E5074797A6A3E059BB460F8C",
                            "paymentSystem": "18",
                            "paymentSystemName": "Mercado Pago",
                            "value": 192717,
                            "installments": 1,
                            "referenceValue": 192717,
                            "cardHolder": None,
                            "cardNumber": None,
                            "firstDigits": None,
                            "lastDigits": None,
                            "cvv2": None,
                            "expireMonth": None,
                            "expireYear": None,
                            "url": None,
                            "giftCardId": None,
                            "giftCardName": None,
                            "giftCardCaption": None,
                            "redemptionCode": None,
                            "group": "MercadoPago",
                            "tid": "51407909966",
                            "dueDate": None,
                            "connectorResponses": {
                                "Tid": "51407909966",
                                "ReturnCode": None,
                                "Message": None,
                                "acquirer": "MercadoPagoV1",
                            },
                            "giftCardProvider": "MercadoPagoV1",
                            "giftCardAsDiscount": None,
                            "koinUrl": None,
                            "accountId": None,
                            "parentAccountId": None,
                            "bankIssuedInvoiceIdentificationNumber": None,
                            "bankIssuedInvoiceIdentificationNumberFormatted": None,
                            "bankIssuedInvoiceBarCodeNumber": None,
                            "bankIssuedInvoiceBarCodeType": None,
                            "billingAddress": None,
                        }
                    ],
                }
            ],
        },
        "isCheckedIn": False,
        "authorizedDate": "2022-11-11T14:26:31.0000000+00:00",
        "followUpEmail": "6fa08a10c41941d3b3a6380cd216d1e1@ct.vtex.com.br",
        "lastMessage": None,
        "sellers": [
            {
                "id": "1",
                "name": "YUMA S.A.",
                "logo": "",
                "fulfillmentEndpoint": "http://fulfillment.vtexcommerce.com.br/api/fulfillment?an=calzadosnicoar",
            }
        ],
        "hostname": "calzadosnicoar",
        "marketingData": None,
        "isCompleted": True,
        "merchantName": None,
        "itemMetadata": {
            "Items": [
                {
                    "Id": "5927",
                    "Seller": "1",
                    "Name": "PELOTA INFLABLE SPORT PLAYA BESTWAY 2097/31004 2097/31004 BESTWAY PELOTA SPORT 2020 VARIOS UNICO",
                    "SkuName": "2097/31004 BESTWAY PELOTA SPORT 2020 VARIOS UNICO",
                    "ProductId": "883",
                    "RefId": "628925#UNICO#VARIOS",
                    "Ean": None,
                    "ImageUrl": "http://calzadosnicoar.vteximg.com.br/arquivos/ids/42399444-55-55/4922a_luuhxj.jpg?v=638037321446200000",
                    "DetailUrl": "/2097-31004-bestway-pelota-sport-2020-varios-unico-628925/p",
                    "AssemblyOptions": [],
                }
            ]
        },
        "value": 192717,
        "subscriptionData": None,
        "affiliateId": "",
        "commercialConditionData": None,
    }


vtex: VtexIntegration = VtexIntegration()


def test_order_creation_ok(test_order):
    order: Core_Order = vtex.create_order_webhook(test_order)
    assert order.store_order_id == "1275500509905-01"
    assert order.source == VTEX
    assert len(order.items) == 1


def test_order_creation_fail(test_order):
    del(test_order["orderId"])
    try:
        order: Core_Order = vtex.create_order_webhook(test_order)
        pytest.fail("Should have failed because there's no orderId")
    except ValidationError as ve:
        var = ve.args[0][0]
        assert var._loc == 'orderId'
